# Generated by Django 2.1.3 on 2018-11-22 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_device', models.CharField(max_length=15)),
                ('timestamp', models.DateTimeField()),
                ('data', models.DecimalField(decimal_places=3, max_digits=15)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('brand', models.CharField(max_length=20)),
                ('device', models.CharField(max_length=255)),
                ('installed_at', models.DateField()),
                ('expired_at', models.DateField()),
                ('active', models.BooleanField()),
            ],
        ),
    ]
